# Generated by Django 2.1.15 on 2020-07-05 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_name', models.CharField(max_length=20)),
                ('edu_content', models.TextField()),
                ('edu_data_start', models.DateField()),
                ('edu_data_finish', models.DateField()),
            ],
            options={
                'ordering': ['-edu_data_start'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_name', models.CharField(max_length=20)),
                ('ex_content', models.TextField()),
                ('ex_data_start', models.DateField()),
                ('ex_data_finish', models.DateField()),
            ],
            options={
                'ordering': ['-ex_data_start'],
            },
        ),
        migrations.CreateModel(
            name='Github',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_reponame', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20)),
                ('project_start', models.DateField()),
                ('project_finsh', models.DateField()),
                ('project_role', models.CharField(max_length=20)),
                ('project_skill', models.CharField(max_length=200)),
                ('project_content', models.TextField()),
                ('project_img', models.ImageField(blank=True, upload_to='media')),
            ],
            options={
                'ordering': ['-project_start'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_kind', models.CharField(max_length=20)),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_img', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usercontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=15)),
                ('introduce', models.CharField(max_length=200)),
                ('develop_content1', models.CharField(max_length=20)),
                ('develop_content2', models.CharField(max_length=20)),
                ('develop_content3', models.CharField(max_length=20)),
                ('develop_content4', models.CharField(max_length=20)),
                ('develop_content5', models.CharField(max_length=20)),
                ('develop_content6', models.CharField(max_length=20)),
                ('all_skills', models.ManyToManyField(null=True, related_name='all_contents', to='portfolios.Skill')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mains.Color')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='Usercontent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolios.Usercontent'),
        ),
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolios.Github'),
        ),
        migrations.AddField(
            model_name='experience',
            name='usercontent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolios.Usercontent'),
        ),
        migrations.AddField(
            model_name='education',
            name='usercontent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolios.Usercontent'),
        ),
    ]
