# Generated by Django 2.1.15 on 2020-07-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontent',
            name='all_skills',
            field=models.ManyToManyField(related_name='all_contents', to='portfolios.Skill'),
        ),
    ]
