# Generated by Django 2.1.15 on 2020-07-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontent',
            name='develop_content1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usercontent',
            name='develop_content2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usercontent',
            name='develop_content3',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usercontent',
            name='develop_content4',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usercontent',
            name='develop_content5',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usercontent',
            name='develop_content6',
            field=models.CharField(max_length=20),
        ),
    ]
