# Generated by Django 2.1.15 on 2020-07-05 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_auto_20200705_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_name', models.CharField(max_length=20)),
                ('edu_content', models.TextField()),
                ('edu_data_start', models.DateField()),
                ('edu_data_finish', models.DateField()),
                ('edu_num', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_name', models.CharField(max_length=20)),
                ('ex_content', models.TextField()),
                ('ex_data_start', models.DateField()),
                ('ex_data_finish', models.DateField()),
                ('ex_num', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['-ex_data_start'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20)),
                ('project_start', models.DateField()),
                ('project_finsh', models.DateField()),
                ('project_role', models.CharField(max_length=20)),
                ('project_skill', models.CharField(max_length=200)),
                ('project_content', models.TextField()),
                ('project_img', models.ImageField(upload_to='')),
                ('project_num', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['-project_start'],
            },
        ),
        migrations.AlterField(
            model_name='usercontent',
            name='all_skills',
            field=models.ManyToManyField(null=True, related_name='all_contents', to='portfolios.Skill'),
        ),
        migrations.AlterField(
            model_name='usercontent',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mains.Color'),
        ),
        migrations.AddField(
            model_name='project',
            name='Usercontent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Usercontent'),
        ),
        migrations.AddField(
            model_name='experience',
            name='usercontent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Usercontent'),
        ),
        migrations.AddField(
            model_name='education',
            name='usercontent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Usercontent'),
        ),
    ]
