# Generated by Django 2.1.15 on 2020-07-05 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_auto_20200705_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontent',
            name='all_skills',
            field=models.ManyToManyField(null=True, related_name='all_contents', to='portfolios.Skill'),
        ),
        migrations.AlterField(
            model_name='usercontent',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mains.Color'),
        ),
    ]
