# Generated by Django 2.1.15 on 2020-07-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_auto_20200704_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontent',
            name='allskill',
        ),
        migrations.AddField(
            model_name='usercontent',
            name='all_skills',
            field=models.ManyToManyField(related_name='all_contents', to='portfolios.Skill'),
        ),
    ]
