# Generated by Django 2.1.15 on 2020-07-05 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_auto_20200705_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-edu_data_start']},
        ),
    ]
