# Generated by Django 2.1.15 on 2020-07-05 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_auto_20200705_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='ex_num',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_num',
        ),
        migrations.AlterField(
            model_name='education',
            name='usercontent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolios.Usercontent'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='usercontent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolios.Usercontent'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Usercontent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolios.Usercontent'),
        ),
    ]
