# Generated by Django 2.1.15 on 2020-07-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_auto_20200705_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='edu_num',
        ),
    ]
