# Generated by Django 2.1.15 on 2020-07-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_auto_20200705_1714'),
        ('portfolios', '0006_remove_education_edu_num'),
    ]

    operations = [
    ]
