# Generated by Django 2.1.15 on 2020-07-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0012_github_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='github',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github',
        ),
        migrations.AddField(
            model_name='project',
            name='git_reponame',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Github',
        ),
    ]
