# Generated by Django 2.1.15 on 2020-07-05 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0013_auto_20200706_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Github',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_reponame', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='git_reponame',
        ),
        migrations.AddField(
            model_name='usercontent',
            name='github',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolios.Github'),
        ),
    ]
