# Generated by Django 2.1.15 on 2020-07-05 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0014_auto_20200706_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontent',
            name='github',
        ),
    ]
