# Generated by Django 2.1.15 on 2020-07-05 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0015_remove_usercontent_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolios.Github'),
        ),
    ]
