# Generated by Django 2.1.15 on 2020-07-04 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color1', models.CharField(max_length=20)),
                ('color2', models.CharField(max_length=20)),
                ('color3', models.CharField(max_length=20)),
                ('color4', models.CharField(max_length=20)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mains.Post')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mains.Post'),
            preserve_default=False,
        ),
    ]
